'use strict';
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])), f=(n,d=2)=>Number.isFinite(n)?n.toLocaleString(undefined,{maximumFractionDigits:d,minimumFractionDigits:d}):'—';
const names={ANA:'Anaheim Ducks',ARI:'Arizona Coyotes',ATL:'Atlanta Thrashers',BOS:'Boston Bruins',BUF:'Buffalo Sabres',CAR:'Carolina Hurricanes',CBJ:'Columbus Blue Jackets',CGY:'Calgary Flames',CHI:'Chicago Blackhawks',COL:'Colorado Avalanche',DAL:'Dallas Stars',DET:'Detroit Red Wings',EDM:'Edmonton Oilers',FLA:'Florida Panthers',LAK:'Los Angeles Kings',MIN:'Minnesota Wild',MTL:'Montréal Canadiens',NJD:'New Jersey Devils',NSH:'Nashville Predators',NYI:'New York Islanders',NYR:'New York Rangers',OTT:'Ottawa Senators',PHI:'Philadelphia Flyers',PIT:'Pittsburgh Penguins',SEA:'Seattle Kraken',SJS:'San Jose Sharks',STL:'St. Louis Blues',TBL:'Tampa Bay Lightning',TOR:'Toronto Maple Leafs',UTA:'Utah Mammoth',VAN:'Vancouver Canucks',VGK:'Vegas Golden Knights',WPG:'Winnipeg Jets',WSH:'Washington Capitals'};
const code=t=>({'L.A':'LAK','T.B':'TBL','S.J':'SJS','N.J':'NJD',PHX:'ARI',ARZ:'ARI',UHC:'UTA',LA:'LAK',TB:'TBL',NJ:'NJD',SJ:'SJS'})[t]||t;
const title=(t,y)=>t==='UTA'&&y==='2024'?'Utah Hockey Club':names[t]||t;
const seasonLabel=y=>`${y}–${String(+y+1).slice(-2)}`;
const asset='https://notmyneon.github.io/MagpiePlayer/assets/';
const logo=t=>`<img class="team-logo" src="${asset}nhl/${encodeURIComponent(t==='ATL'?'WPG':t)}.svg" alt="${esc(names[t]||t)} logo">`;
const brand=()=>`<img class="magpie-logo" src="${asset}magpie-hockey.png" alt="Magpie Hockey">`;
let rows=[],results={},years=[],cache=new Map(),sortKey="magpie",sortDir="desc",rankingYears=new Set();
function score(r){const den=r.shotsAgainst/r.minutes*60+r.goalsAgainst+r.minorPenalties;return den>0?(r.blocked+r.hits+r.takeaways)/den*10:0}
function included(r,year,scope=$('scope').value){if(r.year!==year)return false;return scope==='all'||scope==='playoffs'&&r.type===3||scope==='regular'&&r.type===2||scope==='preseason'&&r.type===1}
function outcome(r){
 const official=results[r.gameId];
 if(official){const winner=code(official[0]);return {win:r.team===winner,end:official[1],official:true,goals:r.team===code(official[4])?official[2]:official[3],oppGoals:r.team===code(official[4])?official[3]:official[2]}}
 if(r.goalsFor!==r.goalsAgainst)return {win:r.goalsFor>r.goalsAgainst,end:r.minutes>60.01?'OT':'REG',official:false,goals:r.goalsFor,oppGoals:r.goalsAgainst};
 return null;
}
function magpieMatch(r,mode='all'){
 if(mode==='all')return true;if(!Number.isFinite(r.magpie)||!Number.isFinite(r.opponentMagpie))return false;
 const d=r.magpie-r.opponentMagpie;return mode==='leading'?d>1e-9:mode==='trailing'?d< -1e-9:Math.abs(d)<=1e-9;
}
function summarize(selected,team,year,scope){
 if(!selected.length)return null;
 const a={team,year,scope,gp:0,wins:0,losses:0,otl:0,unknown:0,points:0,magpie:0,against:0,hits:0,blocked:0,takeaways:0,goalsFor:0,goalsAgainst:0,soWins:0,soLosses:0,otWins:0,otLosses:0};
 for(const r of selected){a.gp++;a.magpie+=r.magpie;a.against+=r.opponentMagpie;for(const k of ['hits','blocked','takeaways','goalsFor','goalsAgainst'])a[k]+=r[k];const o=outcome(r);if(o?.end==='OT'){if(o.win)a.otWins++;else a.otLosses++;}if(!o)a.unknown++;else if(o.win){a.wins++;a.points+=2;if(o.end==='SO')a.soWins++}else if(r.type!==3&&o.end!=='REG'){a.otl++;a.points++;if(o.end==='SO')a.soLosses++}else a.losses++;}
 a.magpie/=a.gp;a.against/=a.gp;a.pct=a.unknown?NaN:a.wins/a.gp*100;
 for(const k of ['hits','blocked','takeaways'])a[k+'PerGame']=a[k]/a.gp;return a;
}
function aggregates(year,scope=$('scope').value,mode='all'){
 const key=year+'|'+scope+'|'+mode;if(cache.has(key))return cache.get(key);
 const groups=new Map();for(const r of rows){if(!included(r,year,scope)||!magpieMatch(r,mode))continue;if(!groups.has(r.team))groups.set(r.team,[]);groups.get(r.team).push(r)}
 const out=[...groups].map(([team,rs])=>summarize(rs,team,year,scope));cache.set(key,out);return out;
}
function leagueAggregate(year,scope=$('scope').value,mode='all'){
 return summarize(rows.filter(r=>included(r,year,scope)&&magpieMatch(r,mode)),'NHL',year,scope);
}

function record(a){if(!a)return'—';return `${a.wins}–${a.losses}${a.scope==='playoffs'?'':'–'+a.otl}${a.unknown?' + '+a.unknown+' pending':''}`}

function pts(a){return a.unknown?`${a.points}*`:String(a.points)}
function metric(label,value,note=''){return `<div class="metric"><span>${esc(label)}</span><strong>${esc(value)}</strong><small>${esc(note)}</small></div>`}
function cardHeader(label,sub){return `<div class="card-header"><div><span class="eyebrow">${esc(sub)}</span><div class="card-title">${esc(label)}</div></div>${brand()}</div>`}
function options(el,values,preferred,labels=v=>v){const prev=preferred??el.value;el.innerHTML=values.map(v=>`<option value="${esc(v)}">${esc(labels(v))}</option>`).join('');if(values.includes(prev))el.value=prev}
function seasonTeams(y,scope=$('scope').value){return aggregates(y,scope).map(a=>a.team).sort((a,b)=>title(a,y).localeCompare(title(b,y)))}

function populateTeams(){const ts=seasonTeams($('season').value);for(const id of ['team','gameTeam'])options($(id),ts,undefined,t=>title(t,$('season').value));options($('standingsTeam'),['all','NHL',...ts],undefined,t=>t==='all'?'All teams':t==='NHL'?'NHL as a whole':title(t,$('season').value));syncCompare();}

function syncCompare(){for(const suffix of ['A','B']){const y=$('year'+suffix).value;options($('compare'+suffix),seasonTeams(y,$('scope'+suffix).value),undefined,t=>title(t,y))}}

function setView(view){if(!['standings','teams','compare','games','timeline'].includes(view))view='standings';document.querySelector('.global-controls').hidden=view==='compare';document.querySelectorAll('[data-panel]').forEach(s=>s.hidden=s.dataset.panel!==view);document.querySelectorAll('[data-export]').forEach(b=>b.onclick=()=>exportCard(b));document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));history.replaceState(null,'','#'+view);renderVisible(view)}
function renderVisible(view=location.hash.slice(1)||'standings'){if(view==='standings')renderStandings();if(view==='teams')renderTeam();if(view==='compare')renderCompare();if(view==='games')renderGames();if(view==='timeline')renderTimeline()}
function sortedStandings(data){
 const ranked=data.slice().sort((a,b)=>b.magpie-a.magpie||a.team.localeCompare(b.team)).map((a,i)=>({...a,rank:i+1}));
 return ranked.sort((a,b)=>{let cmp;if(sortKey==='team')cmp=title(a.team,a.year).localeCompare(title(b.team,b.year));else{const v=a[sortKey],w=b[sortKey];if(!Number.isFinite(v)||!Number.isFinite(w))return Number.isFinite(v)?-1:Number.isFinite(w)?1:0;cmp=v-w}return (sortDir==='asc'?cmp:-cmp)||a.team.localeCompare(b.team)});
}
function renderStandings(){
 const year=$('season').value,mode=$('magpieFilter').value||'all',chosen=$('standingsTeam').value||'all';let all=sortedStandings(aggregates(year,$('scope').value,mode));const league=leagueAggregate(year,$('scope').value,mode);
 if(chosen==='NHL')all=league?[{...league,rank:'—'}]:[];else if(chosen!=='all')all=all.filter(a=>a.team===chosen);
 const row=a=>`<tr ${a.team==='NHL'?'class="league-row"':`data-team="${a.team}" tabindex="0"`}><td>${a.rank}</td><td><span class="team-cell">${a.team==='NHL'?'<strong>NHL</strong>':logo(a.team)}${a.team==='NHL'?'League total':esc(title(a.team,a.year))}</span></td><td>${a.gp}</td><td>${a.wins}</td><td>${a.losses}</td><td>${a.otl}</td><td>${pts(a)}</td><td>${f(a.pct,1)}${Number.isFinite(a.pct)?'%':''}</td><td class="score">${f(a.magpie)}</td><td>${f(a.against)}</td><td>${f(a.hits,0)}</td><td>${f(a.blocked,0)}</td><td>${f(a.takeaways,0)}</td></tr>`;
 $('standingsRows').innerHTML=all.map(row).join('')+(chosen==='all'&&league?row({...league,rank:'—'}):'');
 $('standingsRows').querySelectorAll('[data-team]').forEach(tr=>{const open=()=>{$('team').value=tr.dataset.team;setView('teams')};tr.onclick=open;tr.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}}});
 document.querySelectorAll('[data-sort]').forEach(b=>{b.parentElement.setAttribute('aria-sort',b.dataset.sort===sortKey?(sortDir==='asc'?'ascending':'descending'):'none');b.querySelector('.sort-arrow').textContent=b.dataset.sort===sortKey?(sortDir==='asc'?'↑':'↓'):''});
 const lead=all.slice().sort((a,b)=>b.magpie-a.magpie)[0],low=all.slice().sort((a,b)=>a.against-b.against)[0],count=new Set(rows.filter(r=>included(r,year)&&magpieMatch(r,mode)&&(chosen==='all'||chosen==='NHL'||r.team===chosen)).map(r=>r.gameId)).size;
 $('summary').innerHTML=`<div><span class="eyebrow">${chosen==='NHL'?'LEAGUE MAGPIE FOR':'MAGPIE LEADER'}</span><strong>${lead?f(lead.magpie):'—'}</strong><small>${lead?esc(title(lead.team,lead.year)):'No games'}</small></div><div><span class="eyebrow">${chosen==='NHL'?'LEAGUE MAGPIE AGAINST':'LOWEST AGAINST'}</span><strong>${low?f(low.against):'—'}</strong><small>${low?esc(title(low.team,low.year)):'No games'}</small></div><div><span class="eyebrow">GAMES IN VIEW</span><strong>${f(count,0)}</strong><small>${esc(seasonLabel(year))} · ${$('magpieFilter').selectedOptions[0].text}</small></div>`;
}

function leagueRankNote(target,league,value,lower=false,recordMetric=false){
 const eligible=league.filter(x=>Number.isFinite(value(x))),v=target?value(target):NaN;
 if(!Number.isFinite(v))return 'League rank —';
 const rank=1+eligible.filter(x=>lower?value(x)<v-1e-9:value(x)>v+1e-9).length;
 return `League rank ${rank}/${eligible.length}${recordMetric?' · '+f(v,1)+'% wins':''}`;
}
function renderTeam(){const year=$('season').value,scope=$('scope').value,league=aggregates(year),a=league.find(a=>a.team===$('team').value);if(!a){$('teamCard').innerHTML='<p class="empty">No games in this view.</p>';$('teamGames').innerHTML='';return}
 const leading=aggregates(year,scope,'leading'),trailing=aggregates(year,scope,'trailing'),led=leading.find(x=>x.team===a.team),trailed=trailing.find(x=>x.team===a.team),playoffs=scope==='playoffs';
 const specialWins=x=>playoffs?x.otWins:x.soWins,specialLosses=x=>playoffs?x.otLosses:x.soLosses,specialPct=x=>specialWins(x)+specialLosses(x)?specialWins(x)/(specialWins(x)+specialLosses(x))*100:NaN;
 const note=(target,group,value,lower=false,isRecord=false)=>leagueRankNote(target,group,value,lower,isRecord);
 $('teamCard').innerHTML=`<div class="profile-heading"><div class="profile">${logo(a.team)}<div><h2>${esc(title(a.team,a.year))}</h2><span class="eyebrow">${seasonLabel(a.year)} · ${$('scope').selectedOptions[0].text}</span><p class="record" style="margin-top:12px">${record(a)} <small>${pts(a)} points · ${f(a.pct,1)}% wins</small></p></div></div>${brand()}</div><div class="metrics">${metric('Magpie For',f(a.magpie),note(a,league,x=>x.magpie))}${metric('Magpie Against',f(a.against),note(a,league,x=>x.against,true))}${metric('Magpie Differential',f(a.magpie-a.against),note(a,league,x=>x.magpie-x.against))}${metric('Record while leading',record(led),note(led,leading,x=>x.pct,false,true))}${metric('Record while trailing',record(trailed),note(trailed,trailing,x=>x.pct,false,true))}${metric(playoffs?'OT Record':'Shootout Record',specialWins(a)+'–'+specialLosses(a),note(a,league,specialPct,false,true))}${metric('Hits',f(a.hits,0),note(a,league,x=>x.hits))}${metric('Blocked shots',f(a.blocked,0),note(a,league,x=>x.blocked))}${metric('Takeaways',f(a.takeaways,0),note(a,league,x=>x.takeaways))}</div>${a.unknown?'<p class="note">* '+a.unknown+' game outcomes await official lookup.</p>':''}`;
 $('teamCard').querySelectorAll('.metric').forEach((m,i)=>{if(i>=3&&i<=5)m.classList.add('record-metric')});
 const log=rows.filter(r=>r.team===a.team&&included(r,a.year)).sort((a,b)=>b.date.localeCompare(a.date));$('teamGames').innerHTML=gameTable(log);
}

function gameTable(log){return `<table><thead><tr><th>Date</th><th>Opponent</th><th>Score</th><th>Result</th><th>Magpie For</th><th>Magpie Against</th></tr></thead><tbody>${log.map(r=>{const o=outcome(r);return `<tr><td>${r.date}</td><td><span class="team-cell">${logo(r.opponent)}${esc(title(r.opponent,r.year))}</span></td><td>${o?o.goals+'–'+o.oppGoals:r.goalsFor+'–'+r.goalsAgainst}</td><td>${o?(o.win?'W':r.type!==3&&o.end!=='REG'?'OTL':'L')+(o.end!=='REG'?' · '+o.end:''):'Awaiting lookup'}</td><td class="score">${f(r.magpie)}</td><td>${f(r.opponentMagpie)}</td></tr>`}).join('')}</tbody></table>`}
function renderCompare(){
 const a=aggregates($('yearA').value,$('scopeA').value).find(a=>a.team===$('compareA').value),b=aggregates($('yearB').value,$('scopeB').value).find(a=>a.team===$('compareB').value);if(!a||!b){$('compareCard').innerHTML='<p class="empty">Choose teams with games in each selected season and competition.</p>';return}
 const side=(a,suffix)=>`<div class="compare-team">${logo(a.team)}<h3>${esc(title(a.team,a.year))}</h3><span class="eyebrow">${seasonLabel(a.year)} · ${$('scope'+suffix).selectedOptions[0].text}</span><p class="record" style="margin-top:12px">${record(a)}</p></div>`;
 const metrics=[['Magpie For','magpie',2,false],['Magpie Against','against',2,true],['Games','gp',0,false],['Wins','wins',0,false],['Points','points',0,false],['Win %','pct',1,false],['Hits / game','hitsPerGame',2,false],['Blocks / game','blockedPerGame',2,false],['Takeaways / game','takeawaysPerGame',2,false]];
 $('compareCard').innerHTML=cardHeader('Team Comparison','')+`<div class="compare-grid">${side(a,'A')}${side(b,'B')}</div>`+metrics.map(([label,k,d,lower])=>{const v=a[k],w=b[k],known=Number.isFinite(v)&&Number.isFinite(w)&&!(k==='points'&&(a.unknown||b.unknown));return `<div class="comparison-row"><span class="${known&&(lower?v<w:v>w)?'gold':''}">${k==='points'?pts(a):f(v,d)}</span><span>${label}</span><span class="${known&&(lower?w<v:w>v)?'gold':''}">${k==='points'?pts(b):f(w,d)}</span></div>`}).join('');
}

function renderGames(){const log=rows.filter(r=>r.team===$('gameTeam').value&&included(r,$('season').value)).sort((a,b)=>b.date.localeCompare(a.date));options($('game'),log.map(r=>r.id),undefined,id=>{const r=log.find(r=>r.id===id);return r.date+' · '+title(r.team,r.year)+' vs '+title(r.opponent,r.year)});renderGameCard();renderCombined();}
function populateRankingTeams(){const teams=[...new Set(rows.filter(r=>rankingYears.has(r.year)&&included(r,r.year)).map(r=>r.team))].sort((a,b)=>title(a).localeCompare(title(b)));options($('rankingTeamA'),['',...teams],undefined,t=>t?title(t):'All teams');const a=$('rankingTeamA').value;options($('rankingTeamB'),['',...teams.filter(t=>t!==a)],undefined,t=>t?title(t):'All opponents');$('rankingTeamB').disabled=!a;if(!a)$('rankingTeamB').value='';}
function renderRankingYears(){$('allRankingYears').textContent=rankingYears.size===years.length?'Clear seasons':'All seasons';const container=$('rankingYears');container.innerHTML=years.map(y=>`<button type="button" data-ranking-year="${y}" aria-pressed="${rankingYears.has(y)}">${seasonLabel(y)}</button>`).join('');container.querySelectorAll('[data-ranking-year]').forEach(b=>b.onclick=()=>{const y=b.dataset.rankingYear;if(rankingYears.has(y))rankingYears.delete(y);else rankingYears.add(y);renderRankingYears();populateRankingTeams();renderCombined()});}
function combinedGames(selectedYears=rankingYears,ta=$('rankingTeamA').value,tb=$('rankingTeamB').value,order=$('rankingOrder').value){const seen=new Set(),games=[];for(const r of rows){if(!selectedYears.has(r.year)||!included(r,r.year)||ta&&r.team!==ta&&r.opponent!==ta||tb&&r.team!==tb&&r.opponent!==tb||!Number.isFinite(r.opponentMagpie)||seen.has(r.gameId))continue;seen.add(r.gameId);games.push(r)}return games.sort((a,b)=>(order==='lowest'?1:-1)*((a.magpie+a.opponentMagpie)-(b.magpie+b.opponentMagpie))||a.date.localeCompare(b.date)||a.gameId.localeCompare(b.gameId));}
function renderCombined(){const games=combinedGames(),count=+$('rankingCount').value||10,ta=$('rankingTeamA').value,tb=$('rankingTeamB').value,scope=$('scope').selectedOptions[0].text;const label=$('rankingOrder').value==='lowest'?'Lowest':'Highest',selected=[...rankingYears].sort((a,b)=>+a-+b).map(seasonLabel).join(', '),matchup=ta?title(ta)+(tb?' vs '+title(tb):' · All opponents'):'All NHL teams';
 $('combinedCard').innerHTML=cardHeader(label+' Combined Magpie Games',scope)+`<p class="ranking-subtitle">${esc(matchup)}</p><p class="note">${esc(selected||'Select at least one season')}</p>`+(games.length?games.slice(0,count).map((r,i)=>`<div class="ranked-game"><strong>${i+1}</strong><div><span class="team-cell">${logo(r.team)}${esc(title(r.team,r.year))}<span>vs</span>${logo(r.opponent)}${esc(title(r.opponent,r.year))}</span><span class="game-date">${r.date} · ${r.team} ${f(r.magpie)} / ${r.opponent} ${f(r.opponentMagpie)}</span></div><strong class="combined-value">${f(r.magpie+r.opponentMagpie)}</strong></div>`).join(''):'<p class="empty">No games match these filters.</p>');
}

function renderGameCard(){const r=rows.find(r=>r.id===$('game').value);if(!r){$('gameCard').innerHTML='<p class="empty">No games in this view.</p>';return}const o=outcome(r),opponent=rows.find(x=>x.gameId===r.gameId&&x.team===r.opponent);const sideStats=x=>`<div class="game-stat-side"><span class="eyebrow">MAGPIE SCORE</span><div class="game-magpie">${x?f(x.magpie):'—'}</div><div class="game-components">${['blocked','hits','takeaways'].map((k,i)=>`<div><strong>${x?f(x[k],0):'—'}</strong><span>${['Blocks','Hits','Takeaways'][i]}</span></div>`).join('')}</div>`;
 $('gameCard').innerHTML=cardHeader('Game Recap',r.date+' · '+seasonLabel(r.year))+`<div class="versus"><div>${logo(r.team)}<h3>${esc(title(r.team,r.year))}</h3><div class="final-score">${o?o.goals:r.goalsFor}</div></div><div><span class="result-badge">${o?o.end:'PENDING'}</span><p class="note">FINAL${o?'':' RESULT LOOKUP'}</p></div><div>${logo(r.opponent)}<h3>${esc(title(r.opponent,r.year))}</h3><div class="final-score">${o?o.oppGoals:r.goalsAgainst}</div></div></div><div class="game-stat-grid">${sideStats(r)}${sideStats(opponent)}</div>${!o?'<p class="note">Shootout winner awaits the official NHL lookup.</p>':''}`;
}

function timelineLeague(year){const a=leagueAggregate(year),teams=aggregates(year);if(!a)return null;return {...a,points:a.points/teams.length};}
function renderTimeline(){const metric=$('metric').value,a=$('timelineA').value,b=$('timelineB').value,series=t=>years.slice().reverse().map(y=>({year:y,a:t==='NHL'?timelineLeague(y):aggregates(y).find(r=>r.team===t)})).filter(p=>p.a&&Number.isFinite(p.a[metric])&&!(metric==='points'&&p.a.unknown));const sa=series(a),sb=b?series(b):[],all=[...sa,...sb];if(!all.length){$('timelineCard').innerHTML='<p class="empty">No completed data for this metric.</p>';return}
 const w=1000,h=360,left=65,right=30,top=25,bottom=50,minY=Math.min(...all.map(p=>p.a[metric])),maxY=Math.max(...all.map(p=>p.a[metric])),lo=Math.max(0,minY-(maxY-minY)*.15),hi=maxY+(maxY-minY)*.15||1,chron=years.slice().reverse(),x=y=>left+chron.indexOf(y)/(chron.length-1||1)*(w-left-right),y=v=>top+(hi-v)/(hi-lo||1)*(h-top-bottom);
 let svg='';for(let i=0;i<5;i++){const v=lo+(hi-lo)*i/4;svg+=`<line x1="${left}" y1="${y(v)}" x2="${w-right}" y2="${y(v)}" stroke="#2e4448"/><text x="${left-12}" y="${y(v)+4}" text-anchor="end">${f(v,metric==='points'?0:1)}</text>`}chron.forEach((yr,i)=>{if(i%2===0||i===chron.length-1)svg+=`<text x="${x(yr)}" y="${h-15}" text-anchor="middle">${seasonLabel(yr)}</text>`});
 for(const [s,color] of [[sa,'#57e2c2'],[sb,'#ffd16c']]){let prev=null;for(const p of s){if(prev&&+p.year===+prev.year+1)svg+=`<line x1="${x(prev.year)}" y1="${y(prev.a[metric])}" x2="${x(p.year)}" y2="${y(p.a[metric])}" stroke="${color}" stroke-width="3"/>`;svg+=`<circle cx="${x(p.year)}" cy="${y(p.a[metric])}" r="5" fill="${color}"><title>${esc(title(p.a.team,p.year))} · ${seasonLabel(p.year)}: ${f(p.a[metric])}</title></circle>`;prev=p}}
 $('timelineCard').innerHTML=cardHeader($('metric').selectedOptions[0].text+' · Season Timeline',$('scope').selectedOptions[0].text)+`<div class="legend"><span>${logo(a)} ${esc(title(a,$('season').value))}</span>${b?`<span>${b==='NHL'?'<span class="league-mark">NHL</span>':logo(b)} ${b==='NHL'?'League average':esc(title(b,$('season').value))}</span>`:''}</div><div class="chart-wrap"><svg class="chart" viewBox="0 0 ${w} ${h}" role="img" aria-label="${esc($('metric').selectedOptions[0].text)} by season">${svg}</svg></div>`;
}
async function exportCard(button){
 const card=$(button.dataset.export),status=button.parentElement.querySelector('.export-status');button.disabled=true;status.textContent='Creating image…';
 const stage=document.createElement('div');stage.style.cssText='position:fixed;left:-20000px;top:0;width:1000px';
 try{if(!window.htmlToImage)throw Error('Image renderer unavailable');const copy=card.cloneNode(true);copy.style.width='1000px';stage.append(copy);document.body.append(stage);await document.fonts.ready;await Promise.all([...copy.querySelectorAll('img')].map(img=>img.decode().catch(()=>{})));const height=Math.ceil(copy.getBoundingClientRect().height);const canvas=await window.htmlToImage.toCanvas(copy,{width:1000,height,pixelRatio:1.5,backgroundColor:'#101c20'});const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw Error('Image encoding failed');const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='magpie-'+button.dataset.export+'-'+$('season').value+'.png';link.click();setTimeout(()=>URL.revokeObjectURL(url),30000);status.textContent='Image downloaded';}catch(e){status.textContent='Could not create the image. '+e.message}finally{stage.remove();button.disabled=false}
}
async function init(){try{const [d,m]=await Promise.all(['data.json','game-meta.json'].map(async p=>{const res=await fetch(p);if(!res.ok)throw Error(p+' '+res.status);return res.json()}));try{const res=await fetch('results.json',{cache:'no-store'});if(res.ok)results=await res.json()}catch(_){results={}}
 rows=d.map(r=>{const meta=m[r.id];if(!meta)throw Error('Missing metadata for '+r.id);const team=code(r.id.split('-')[0]),official=results[meta[0]],opponent=official?(code(official[4])===team?code(official[5]):code(official[4])):code(r.opponent);return {...r,team,opponent,gameId:meta[0],goalsFor:meta[1],type:+meta[0].slice(4,6),magpie:score(r)}});const paired=new Map(rows.map(r=>[r.gameId+'|'+r.team,r]));for(const r of rows)r.opponentMagpie=paired.get(r.gameId+'|'+r.opponent)?.magpie??NaN;
 years=[...new Set(rows.map(r=>r.year))].sort((a,b)=>+b-+a);const defaultYear=years.find(y=>rows.filter(r=>r.year===y&&r.type===2).length>=1000)||years[0];for(const id of ['season','yearA','yearB'])options($(id),years,defaultYear,seasonLabel);if(rows.some(r=>r.type===1))$('scope').insertAdjacentHTML('beforeend','<option value="preseason">Preseason</option>');populateTeams();rankingYears=new Set([defaultYear]);renderRankingYears();populateRankingTeams();const allTeams=[...new Set(rows.map(r=>r.team))].sort((a,b)=>title(a).localeCompare(title(b)));options($('timelineA'),allTeams,'CGY',t=>title(t));options($('timelineB'),['','NHL',...allTeams],'NHL',t=>t==='NHL'?'League average':t?title(t):'No comparison');$('compareB').selectedIndex=Math.min(1,$('compareB').options.length-1);
 document.querySelectorAll('[data-export]').forEach(b=>b.onclick=()=>exportCard(b));document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('season').onchange=()=>{populateTeams();renderVisible()};$('scope').onchange=()=>{populateTeams();populateRankingTeams();renderVisible()};for(const id of ['standingsTeam','magpieFilter'])$(id).onchange=renderStandings;document.querySelectorAll('[data-sort]').forEach(b=>b.onclick=()=>{const k=b.dataset.sort;if(sortKey===k)sortDir=sortDir==='asc'?'desc':'asc';else{sortKey=k;sortDir=['team','rank','against','losses','otl'].includes(k)?'asc':'desc'}renderStandings()});$('team').onchange=renderTeam;for(const id of ['yearA','yearB','scopeA','scopeB'])$(id).onchange=()=>{syncCompare();renderCompare()};for(const id of ['compareA','compareB'])$(id).onchange=renderCompare;$('gameTeam').onchange=renderGames;$('game').onchange=renderGameCard;$('rankingTeamA').onchange=()=>{populateRankingTeams();renderCombined()};for(const id of ['rankingTeamB','rankingOrder','rankingCount'])$(id).onchange=renderCombined;$('allRankingYears').onclick=()=>{rankingYears=new Set(rankingYears.size===years.length?[]:years);renderRankingYears();populateRankingTeams();renderCombined()};for(const id of ['timelineA','timelineB','metric'])$(id).onchange=renderTimeline;window.onhashchange=()=>setView(location.hash.slice(1));const pending=rows.filter(r=>!outcome(r)).length;$('status').textContent=`${rows.length.toLocaleString()} team-game records · ${Object.keys(results).length.toLocaleString()} official results matched${pending?' · '+pending.toLocaleString()+' team outcomes awaiting lookup':''}`;setView(location.hash.slice(1));
 }catch(e){console.error(e);$('status').textContent='Could not load team data. Refresh to retry. '+e.message}}
init();
