'use strict';
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])), f=(n,d=2)=>Number.isFinite(n)?n.toLocaleString(undefined,{maximumFractionDigits:d,minimumFractionDigits:d}):'—';
const names={ANA:'Anaheim Ducks',ARI:'Arizona Coyotes',ATL:'Atlanta Thrashers',BOS:'Boston Bruins',BUF:'Buffalo Sabres',CAR:'Carolina Hurricanes',CBJ:'Columbus Blue Jackets',CGY:'Calgary Flames',CHI:'Chicago Blackhawks',COL:'Colorado Avalanche',DAL:'Dallas Stars',DET:'Detroit Red Wings',EDM:'Edmonton Oilers',FLA:'Florida Panthers',LAK:'Los Angeles Kings',MIN:'Minnesota Wild',MTL:'Montréal Canadiens',NJD:'New Jersey Devils',NSH:'Nashville Predators',NYI:'New York Islanders',NYR:'New York Rangers',OTT:'Ottawa Senators',PHI:'Philadelphia Flyers',PIT:'Pittsburgh Penguins',SEA:'Seattle Kraken',SJS:'San Jose Sharks',STL:'St. Louis Blues',TBL:'Tampa Bay Lightning',TOR:'Toronto Maple Leafs',UTA:'Utah Mammoth',VAN:'Vancouver Canucks',VGK:'Vegas Golden Knights',WPG:'Winnipeg Jets',WSH:'Washington Capitals'};
const code=t=>({'L.A':'LAK','T.B':'TBL','S.J':'SJS','N.J':'NJD',PHX:'ARI',ARZ:'ARI',UHC:'UTA',LA:'LAK',TB:'TBL',NJ:'NJD',SJ:'SJS'})[t]||t;
const title=(t,y)=>t==='UTA'&&y==='2024'?'Utah Hockey Club':names[t]||t;
const seasonLabel=y=>`${y}–${String(+y+1).slice(-2)}`;
const asset='https://notmyneon.github.io/MagpiePlayer/assets/';
const logo=t=>`<img class="team-logo" src="${asset}nhl/${encodeURIComponent(t==='ATL'?'WPG':t)}.svg" alt="${esc(names[t]||t)} logo">`;
const brand=()=>`<img class="magpie-logo" src="${asset}magpie-hockey.png" alt="Magpie Hockey">`;
let rows=[],results={},years=[],cache=new Map();
function score(r){const den=r.shotsAgainst/r.minutes*60+r.goalsAgainst+r.minorPenalties;return den>0?(r.blocked+r.hits+r.takeaways)/den*10:0}
function included(r,year,scope=$('scope').value){if(r.year!==year)return false;return scope==='all'||scope==='playoffs'&&r.type===3||scope==='regular'&&r.type===2||scope==='preseason'&&r.type===1}
function outcome(r){
 const official=results[r.gameId];
 if(official){const winner=code(official[0]);return {win:r.team===winner,end:official[1],official:true,goals:r.team===code(official[4])?official[2]:official[3],oppGoals:r.team===code(official[4])?official[3]:official[2]}}
 if(r.goalsFor!==r.goalsAgainst)return {win:r.goalsFor>r.goalsAgainst,end:r.minutes>60.01?'OT':'REG',official:false,goals:r.goalsFor,oppGoals:r.goalsAgainst};
 return null;
}
function aggregates(year,scope=$('scope').value){
 const key=year+'|'+scope;if(cache.has(key))return cache.get(key);
 const selected=rows.filter(r=>included(r,year,scope)),m=new Map();
 for(const r of selected){if(!m.has(r.team))m.set(r.team,{team:r.team,year,gp:0,wins:0,losses:0,otl:0,unknown:0,points:0,magpie:0,against:0,hits:0,blocked:0,takeaways:0,goalsFor:0,goalsAgainst:0,soWins:0,soLosses:0});const a=m.get(r.team);a.gp++;a.magpie+=r.magpie;a.against+=r.opponentMagpie;for(const k of ['hits','blocked','takeaways','goalsFor','goalsAgainst'])a[k]+=r[k];const o=outcome(r);if(!o)a.unknown++;else if(o.win){a.wins++;a.points+=2;if(o.end==='SO')a.soWins++}else if(r.type!==3&&o.end!=='REG'){a.otl++;a.points++;if(o.end==='SO')a.soLosses++}else a.losses++;}
 const out=[...m.values()].map(a=>({...a,magpie:a.magpie/a.gp,against:a.against/a.gp,pct:a.unknown?NaN:a.wins/a.gp*100}));cache.set(key,out);return out;
}
function record(a){if(!a)return'—';return `${a.wins}–${a.losses}${$('scope').value==='playoffs'?'':'–'+a.otl}${a.unknown?' + '+a.unknown+' pending':''}`}
function pts(a){return a.unknown?`${a.points}*`:String(a.points)}
function metric(label,value,note=''){return `<div class="metric"><span>${esc(label)}</span><strong>${esc(value)}</strong><small>${esc(note)}</small></div>`}
function cardHeader(label,sub){return `<div class="card-header"><div><span class="eyebrow">${esc(sub)}</span><div class="card-title">${esc(label)}</div></div>${brand()}</div>`}
function options(el,values,preferred,labels=v=>v){const prev=preferred??el.value;el.innerHTML=values.map(v=>`<option value="${esc(v)}">${esc(labels(v))}</option>`).join('');if(values.includes(prev))el.value=prev}
function seasonTeams(y){return aggregates(y).map(a=>a.team).sort((a,b)=>title(a,y).localeCompare(title(b,y)))}
function populateTeams(){const ts=seasonTeams($('season').value);for(const id of ['team','gameTeam'])options($(id),ts,undefined,t=>title(t,$('season').value));syncCompare();}
function syncCompare(){for(const suffix of ['A','B']){const y=$('year'+suffix).value;options($('compare'+suffix),seasonTeams(y),undefined,t=>title(t,y))}}
function setView(view){if(!['standings','teams','compare','games','timeline'].includes(view))view='standings';document.querySelectorAll('[data-panel]').forEach(s=>s.hidden=s.dataset.panel!==view);document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));history.replaceState(null,'','#'+view);renderVisible(view)}
function renderVisible(view=location.hash.slice(1)||'standings'){if(view==='standings')renderStandings();if(view==='teams')renderTeam();if(view==='compare')renderCompare();if(view==='games')renderGames();if(view==='timeline')renderTimeline()}
function renderStandings(){
 const sort=$('sort').value,all=aggregates($('season').value).slice();all.sort((a,b)=>sort==='against'?a.against-b.against:(Number.isFinite(b[sort])?b[sort]:-Infinity)-(Number.isFinite(a[sort])?a[sort]:-Infinity)||a.team.localeCompare(b.team));
 $('standingsRows').innerHTML=all.map((a,i)=>`<tr data-team="${a.team}" tabindex="0"><td>${i+1}</td><td><span class="team-cell">${logo(a.team)}${esc(title(a.team,a.year))}</span></td><td>${a.gp}</td><td>${record(a)}</td><td>${pts(a)}</td><td>${f(a.pct,1)}${Number.isFinite(a.pct)?'%':''}</td><td class="score">${f(a.magpie)}</td><td>${f(a.against)}</td><td>${f(a.hits,0)}</td><td>${f(a.blocked,0)}</td><td>${f(a.takeaways,0)}</td></tr>`).join('');
 $('standingsRows').querySelectorAll('[data-team]').forEach(tr=>{const open=()=>{$('team').value=tr.dataset.team;setView('teams')};tr.onclick=open;tr.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}}});
 const lead=all.slice().sort((a,b)=>b.magpie-a.magpie)[0],low=all.slice().sort((a,b)=>a.against-b.against)[0];$('summary').innerHTML=`<div><span class="eyebrow">MAGPIE LEADER</span><strong>${lead?f(lead.magpie):'—'}</strong><small>${lead?esc(title(lead.team,lead.year)):'No games'}</small></div><div><span class="eyebrow">LOWEST AGAINST</span><strong>${low?f(low.against):'—'}</strong><small>${low?esc(title(low.team,low.year)):'No games'}</small></div><div><span class="eyebrow">GAMES IN VIEW</span><strong>${f(all.reduce((n,a)=>n+a.gp,0)/2,0)}</strong><small>${esc(seasonLabel($('season').value))} · ${$('scope').selectedOptions[0].text}</small></div>`;
}
function renderTeam(){const a=aggregates($('season').value).find(a=>a.team===$('team').value);if(!a){$('teamCard').innerHTML='<p class="empty">No games in this view.</p>';$('teamGames').innerHTML='';return}
 const ranks=aggregates(a.year).slice().sort((a,b)=>b.magpie-a.magpie);$('teamCard').innerHTML=cardHeader('Team Profile',seasonLabel(a.year)+' · '+$('scope').selectedOptions[0].text)+`<div class="profile">${logo(a.team)}<div><span class="eyebrow">${a.gp} GAMES</span><h2>${esc(title(a.team,a.year))}</h2><p class="record">${record(a)} <small>${pts(a)} points · ${f(a.pct,1)}% wins</small></p></div></div><div class="metrics">${metric('Magpie For',f(a.magpie),'League rank '+(ranks.indexOf(a)+1))}${metric('Magpie Against',f(a.against),'Opponent average')}${metric('Goal differential',f(a.goalsFor-a.goalsAgainst,0),'Excludes shootout deciding goal')}${metric('Shootouts',a.soWins+'–'+a.soLosses,'W–L · Official outcomes')}${metric('Hits',f(a.hits,0))}${metric('Blocked shots',f(a.blocked,0))}${metric('Takeaways',f(a.takeaways,0))}${metric('Games played',String(a.gp))}</div>${a.unknown?'<p class="note">* '+a.unknown+' game outcomes await official lookup. The record and points are partial.</p>':''}`;
 const log=rows.filter(r=>r.team===a.team&&included(r,a.year)).sort((a,b)=>b.date.localeCompare(a.date));$('teamGames').innerHTML=gameTable(log);
}
function gameTable(log){return `<table><thead><tr><th>Date</th><th>Opponent</th><th>Score</th><th>Result</th><th>Magpie For</th><th>Magpie Against</th></tr></thead><tbody>${log.map(r=>{const o=outcome(r);return `<tr><td>${r.date}</td><td><span class="team-cell">${logo(r.opponent)}${esc(title(r.opponent,r.year))}</span></td><td>${o?o.goals+'–'+o.oppGoals:r.goalsFor+'–'+r.goalsAgainst}</td><td>${o?(o.win?'W':r.type!==3&&o.end!=='REG'?'OTL':'L')+(o.end!=='REG'?' · '+o.end:''):'Awaiting lookup'}</td><td class="score">${f(r.magpie)}</td><td>${f(r.opponentMagpie)}</td></tr>`}).join('')}</tbody></table>`}
function renderCompare(){
 const a=aggregates($('yearA').value).find(a=>a.team===$('compareA').value),b=aggregates($('yearB').value).find(a=>a.team===$('compareB').value);if(!a||!b){$('compareCard').innerHTML='<p class="empty">Choose teams with games in this view.</p>';return}
 const side=a=>`<div class="compare-team">${logo(a.team)}<h3>${esc(title(a.team,a.year))}</h3><span class="eyebrow">${seasonLabel(a.year)}</span><p class="record" style="margin-top:12px">${record(a)}</p></div>`;
 const metrics=[['Magpie For','magpie',2,false],['Magpie Against','against',2,true],['Games','gp',0,false],['Wins','wins',0,false],['Points','points',0,false],['Win %','pct',1,false],['Hits','hits',0,false],['Blocks','blocked',0,false],['Takeaways','takeaways',0,false]];
 $('compareCard').innerHTML=cardHeader('Team Comparison',$('scope').selectedOptions[0].text)+`<div class="compare-grid">${side(a)}${side(b)}</div>`+metrics.map(([label,k,d,lower])=>{const v=a[k],w=b[k],known=Number.isFinite(v)&&Number.isFinite(w)&&!(k==='points'&&(a.unknown||b.unknown));return `<div class="comparison-row"><span class="${known&&(lower?v<w:v>w)?'gold':''}">${k==='points'?pts(a):f(v,d)}</span><span>${label}</span><span class="${known&&(lower?w<v:w>v)?'gold':''}">${k==='points'?pts(b):f(w,d)}</span></div>`}).join('')+'<p class="note">Yellow marks the higher value, or the lower Magpie Against. Points with * are partial.</p>';
}
function renderGames(){const log=rows.filter(r=>r.team===$('gameTeam').value&&included(r,$('season').value)).sort((a,b)=>b.date.localeCompare(a.date));options($('game'),log.map(r=>r.id),undefined,id=>{const r=log.find(r=>r.id===id);return r.date+' · '+title(r.team,r.year)+' vs '+title(r.opponent,r.year)});renderGameCard();const seen=new Set(),games=[];for(const r of rows.filter(r=>included(r,$('season').value))){if(seen.has(r.gameId))continue;seen.add(r.gameId);games.push(r)}games.sort((a,b)=>(b.magpie+b.opponentMagpie)-(a.magpie+a.opponentMagpie));$('topGames').innerHTML=`<table><thead><tr><th>#</th><th>Game</th><th>Date</th><th>Combined Magpie</th></tr></thead><tbody>${games.slice(0,10).map((r,i)=>`<tr><td>${i+1}</td><td><span class="team-cell">${logo(r.team)}${r.team} vs ${logo(r.opponent)}${r.opponent}</span></td><td>${r.date}</td><td class="score">${f(r.magpie+r.opponentMagpie)}</td></tr>`).join('')}</tbody></table>`}
function renderGameCard(){const r=rows.find(r=>r.id===$('game').value);if(!r){$('gameCard').innerHTML='<p class="empty">No games in this view.</p>';return}const o=outcome(r);$('gameCard').innerHTML=cardHeader('Game Recap',r.date+' · '+seasonLabel(r.year))+`<div class="versus"><div>${logo(r.team)}<h3>${esc(title(r.team,r.year))}</h3><div class="final-score">${o?o.goals:r.goalsFor}</div></div><div><span class="result-badge">${o?o.end:'PENDING'}</span><p class="note">FINAL${o?'':' RESULT LOOKUP'}</p></div><div>${logo(r.opponent)}<h3>${esc(title(r.opponent,r.year))}</h3><div class="final-score">${o?o.oppGoals:r.goalsAgainst}</div></div></div><div class="metrics">${metric(r.team+' Magpie',f(r.magpie))}${metric(r.opponent+' Magpie',f(r.opponentMagpie))}${metric('Combined',f(r.magpie+r.opponentMagpie))}${metric('Game length',f(r.minutes,1),'Minutes')}</div>${!o?'<p class="note">Shootout winner awaits the official NHL lookup. A tied statistical score is not counted as a tie.</p>':''}${o?.end==='SO'?'<p class="note">Official final score includes the shootout deciding goal. Magpie uses the original game statistics.</p>':''}`}
function renderTimeline(){const metric=$('metric').value,a=$('timelineA').value,b=$('timelineB').value,series=t=>years.slice().reverse().map(y=>({year:y,a:aggregates(y).find(r=>r.team===t)})).filter(p=>p.a&&Number.isFinite(p.a[metric])&&!(metric==='points'&&p.a.unknown));const sa=series(a),sb=b?series(b):[],all=[...sa,...sb];if(!all.length){$('timelineCard').innerHTML='<p class="empty">No completed data for this metric.</p>';return}
 const w=1000,h=360,left=65,right=30,top=25,bottom=50,minY=Math.min(...all.map(p=>p.a[metric])),maxY=Math.max(...all.map(p=>p.a[metric])),lo=Math.max(0,minY-(maxY-minY)*.15),hi=maxY+(maxY-minY)*.15||1,chron=years.slice().reverse(),x=y=>left+chron.indexOf(y)/(chron.length-1||1)*(w-left-right),y=v=>top+(hi-v)/(hi-lo||1)*(h-top-bottom);
 let svg='';for(let i=0;i<5;i++){const v=lo+(hi-lo)*i/4;svg+=`<line x1="${left}" y1="${y(v)}" x2="${w-right}" y2="${y(v)}" stroke="#2e4448"/><text x="${left-12}" y="${y(v)+4}" text-anchor="end">${f(v,metric==='points'?0:1)}</text>`}chron.forEach((yr,i)=>{if(i%2===0||i===chron.length-1)svg+=`<text x="${x(yr)}" y="${h-15}" text-anchor="middle">${seasonLabel(yr)}</text>`});
 for(const [s,color] of [[sa,'#57e2c2'],[sb,'#ffd16c']]){let prev=null;for(const p of s){if(prev&&+p.year===+prev.year+1)svg+=`<line x1="${x(prev.year)}" y1="${y(prev.a[metric])}" x2="${x(p.year)}" y2="${y(p.a[metric])}" stroke="${color}" stroke-width="3"/>`;svg+=`<circle cx="${x(p.year)}" cy="${y(p.a[metric])}" r="5" fill="${color}"><title>${esc(title(p.a.team,p.year))} · ${seasonLabel(p.year)}: ${f(p.a[metric])}</title></circle>`;prev=p}}
 $('timelineCard').innerHTML=cardHeader($('metric').selectedOptions[0].text+' · Season Timeline',$('scope').selectedOptions[0].text)+`<div class="legend"><span>${logo(a)} ${esc(title(a,$('season').value))}</span>${b?`<span>${logo(b)} ${esc(title(b,$('season').value))}</span>`:''}</div><div class="chart-wrap"><svg class="chart" viewBox="0 0 ${w} ${h}" role="img" aria-label="${esc($('metric').selectedOptions[0].text)} by season">${svg}</svg></div><p class="note">Hover over a point for its value. Seasons with unavailable outcomes are omitted from record metrics.</p>`;
}
async function init(){try{const [d,m]=await Promise.all(['data.json','game-meta.json'].map(async p=>{const res=await fetch(p);if(!res.ok)throw Error(p+' '+res.status);return res.json()}));try{const res=await fetch('results.json',{cache:'no-store'});if(res.ok)results=await res.json()}catch(_){results={}}
 rows=d.map(r=>{const meta=m[r.id];if(!meta)throw Error('Missing metadata for '+r.id);return {...r,team:code(r.id.split('-')[0]),opponent:code(r.opponent),gameId:meta[0],goalsFor:meta[1],type:+meta[0].slice(4,6),magpie:score(r)}});const paired=new Map(rows.map(r=>[r.gameId+'|'+r.team,r]));for(const r of rows)r.opponentMagpie=paired.get(r.gameId+'|'+r.opponent)?.magpie??NaN;
 years=[...new Set(rows.map(r=>r.year))].sort((a,b)=>+b-+a);const defaultYear=years.find(y=>rows.filter(r=>r.year===y&&r.type===2).length>=1000)||years[0];for(const id of ['season','yearA','yearB'])options($(id),years,defaultYear,seasonLabel);if(rows.some(r=>r.type===1))$('scope').insertAdjacentHTML('beforeend','<option value="preseason">Preseason</option>');populateTeams();const allTeams=[...new Set(rows.map(r=>r.team))].sort((a,b)=>title(a).localeCompare(title(b)));options($('timelineA'),allTeams,'CGY',t=>title(t));options($('timelineB'),['',...allTeams],'',t=>t?title(t):'No comparison');$('compareB').selectedIndex=Math.min(1,$('compareB').options.length-1);
 document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('season').onchange=()=>{populateTeams();renderVisible()};$('scope').onchange=()=>{populateTeams();renderVisible()};$('sort').onchange=renderStandings;$('team').onchange=renderTeam;for(const id of ['yearA','yearB'])$(id).onchange=()=>{syncCompare();renderCompare()};for(const id of ['compareA','compareB'])$(id).onchange=renderCompare;$('gameTeam').onchange=renderGames;$('game').onchange=renderGameCard;for(const id of ['timelineA','timelineB','metric'])$(id).onchange=renderTimeline;window.onhashchange=()=>setView(location.hash.slice(1));const pending=rows.filter(r=>!outcome(r)).length;$('status').textContent=`${rows.length.toLocaleString()} team-game records · ${Object.keys(results).length.toLocaleString()} official results matched${pending?' · '+pending.toLocaleString()+' team outcomes awaiting lookup':''}`;setView(location.hash.slice(1));
 }catch(e){console.error(e);$('status').textContent='Could not load team data. Refresh to retry. '+e.message}}
init();
